# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='enayo del poder', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('gig', 'gig'), ('rehearsal', 'rehearsal')], default='gig', max_length=20),
            preserve_default=False,
        ),
    ]
